import os

# 渲染和交互时间配置(毫秒)
RENDER_DEBOUNCE_MS = 50
IDLE_THRESHOLD_MS = 100

# AI 预测框视觉配置
AI_PEN_COLOR = (255, 0, 0)
AI_PEN_WIDTH = 2

# 硬件环境自适应与 AI 参数动态调优配置
SAFE_VRAM_MARGIN_MB = 500.0
MODEL_VRAM_OVERHEAD_MULTIPLIER = 2.5
VRAM_PER_TILE_MB = 8.0

IO_SPEED_NAS_USB2_MBPS = 10
IO_SPEED_SATA_SSD_MBPS = 30
IO_SPEED_NORMAL_SSD_MBPS = 80

# 硬件画像 EMA (指数移动平均) 进化系数
EMA_ALPHA_NEW = 0.3
EMA_ALPHA_OLD = 0.7

# 智能调优 (Auto-Tuning) 步长重叠率系数
AUTO_STRIDE_RATIO_HIGH = 0.5
AUTO_STRIDE_RATIO_MID = 0.75
AUTO_STRIDE_RATIO_LOW = 0.95

BATCH_SIZE_CAP_NAS_USB2 = 8
BATCH_SIZE_CAP_SATA_SSD = 16
BATCH_SIZE_CAP_NORMAL_SSD = 32
BATCH_SIZE_CAP_NVME_SSD = 64

RAM_THRESHOLD_SMALL_MB = 8192
RAM_THRESHOLD_NORMAL_MB = 16384

TILE_CACHE_LIMIT_SMALL = 100
TILE_CACHE_LIMIT_NORMAL = 300
TILE_CACHE_LIMIT_LARGE = 1000

# 数据库配置
DB_DIR = "data"
DB_FILE = os.path.join(DB_DIR, "wsi_data.db")
DB_DEFAULT_CAPACITY_MB = 150
DB_MIN_CAPACITY_MB = 50

# AI 推理与图像处理配置
AI_PATCH_SIZE = 512
AI_STRIDE = 400
AI_NMS_IOU_THRESH = 0.25
AI_CONF_THRESH = 0.5
AI_MASK_TARGET_LEVEL = 3
AI_MIN_AREA_RATIO = 0.001

# AI 推理与图像处理安全边界配置
AI_PATCH_SIZE_MIN = 128
AI_PATCH_SIZE_MAX = 4096
AI_STRIDE_MIN = 64
AI_STRIDE_MAX = 4096
AI_NMS_IOU_THRESH_MIN = 0.01
AI_NMS_IOU_THRESH_MAX = 1.0
AI_CONF_THRESH_MIN = 0.01
AI_CONF_THRESH_MAX = 1.0
AI_MAX_PATCHES_LIMIT = 100000

# ROI 靶向分析专属配置
ROI_STRIDE_RATIO = 0.5
